name: Deploy ARM Template

on:
		release:
    	types:
      	- published
    	paths:
      	- ".github/workflows/deployContainer.yml"
      	- "templates/azuredeploy.json"

  	pull_request:

env:
    TEMPLATE_PATH: ./templates/azuredeploy.json

jobs:
  deploy-storage-account-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      # - name: Deploy ARM Template
      #   uses: azure/CLI@v1
			# 	with:
			# 		parameters: |
			# 			name=github-action-asp 
			# 			image=github-action-demo
      #     inlineScript: |
			# 			az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP }} --template-file ${{ env.TEMPLATE_PATH }}
						
			- name: 'Build and push image'
				uses: azure/docker-login@v1
				with:
					login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
					username: ${{ secrets.REGISTRY_USERNAME }}
					password: ${{ secrets.REGISTRY_PASSWORD }}
				run: |
						docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.APP_NAME }}:${{ github.sha }}
						docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.APP_NAME }}:${{ github.sha }}
	
			- name: 'Deploy to Azure Container Instances'
				uses: 'azure/aci-deploy@v1'
				with:
					resource-group: ${{ secrets.RESOURCE_GROUP }}
					dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
					image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.APP_NAME }}:${{ github.sha }}
					registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
					registry-username: ${{ secrets.REGISTRY_USERNAME }}
					registry-password: ${{ secrets.REGISTRY_PASSWORD }}
					name: ${{ secrets.APP_NAME }}
					location: 'canada central'